services:
#    core.example:
#        class: CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  host.communicator:
    class: CoreBundle\Service\HostCommunicator
    arguments: []

  analysis:
    class: CoreBundle\Service\Analysis
    arguments: ['@doctrine.orm.entity_manager']